# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jan 16 21:53:07 2014
#      by: pyside-uic 0.2.13 running on PySide 1.1.0
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(530, 385)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/resources/app.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.frame)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.folders = QtGui.QComboBox(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.folders.sizePolicy().hasHeightForWidth())
        self.folders.setSizePolicy(sizePolicy)
        self.folders.setInsertPolicy(QtGui.QComboBox.InsertAtTop)
        self.folders.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.folders.setObjectName("folders")
        self.horizontalLayout.addWidget(self.folders)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.selectFolder = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectFolder.sizePolicy().hasHeightForWidth())
        self.selectFolder.setSizePolicy(sizePolicy)
        self.selectFolder.setObjectName("selectFolder")
        self.horizontalLayout.addWidget(self.selectFolder)
        self.browseFolder = QtGui.QPushButton(self.frame)
        self.browseFolder.setAutoDefault(False)
        self.browseFolder.setObjectName("browseFolder")
        self.horizontalLayout.addWidget(self.browseFolder)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ipAddresses = QtGui.QComboBox(self.frame_2)
        self.ipAddresses.setObjectName("ipAddresses")
        self.horizontalLayout_2.addWidget(self.ipAddresses)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.portNum = QtGui.QSpinBox(self.frame_2)
        self.portNum.setMaximum(65535)
        self.portNum.setProperty("value", 69)
        self.portNum.setObjectName("portNum")
        self.horizontalLayout_2.addWidget(self.portNum)
        self.startButton = QtGui.QToolButton(self.frame_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/resources/media-playback-start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startButton.setIcon(icon1)
        self.startButton.setObjectName("startButton")
        self.horizontalLayout_2.addWidget(self.startButton)
        self.stopButton = QtGui.QToolButton(self.frame_2)
        self.stopButton.setEnabled(False)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/resources/media-playback-stop.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon2)
        self.stopButton.setObjectName("stopButton")
        self.horizontalLayout_2.addWidget(self.stopButton)
        self.verticalLayout.addWidget(self.frame_2)
        self.scrollArea = QtGui.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 516, 245))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.log = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.log.setReadOnly(True)
        self.log.setObjectName("log")
        self.verticalLayout_2.addWidget(self.log)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 530, 21))
        self.menubar.setObjectName("menubar")
        self.menuServer = QtGui.QMenu(self.menubar)
        self.menuServer.setObjectName("menuServer")
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionStart_Server = QtGui.QAction(MainWindow)
        self.actionStart_Server.setIcon(icon1)
        self.actionStart_Server.setObjectName("actionStart_Server")
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionStop_Serving = QtGui.QAction(MainWindow)
        self.actionStop_Serving.setEnabled(False)
        self.actionStop_Serving.setIcon(icon2)
        self.actionStop_Serving.setObjectName("actionStop_Serving")
        self.actionSettings = QtGui.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.actionOpen_Working_Folder = QtGui.QAction(MainWindow)
        self.actionOpen_Working_Folder.setObjectName("actionOpen_Working_Folder")
        self.menuServer.addAction(self.actionStart_Server)
        self.menuServer.addAction(self.actionStop_Serving)
        self.menuServer.addAction(self.actionSettings)
        self.menuServer.addSeparator()
        self.menuServer.addAction(self.actionQuit)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuServer.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.actionQuit, QtCore.SIGNAL("triggered()"), MainWindow.close)
        QtCore.QObject.connect(self.startButton, QtCore.SIGNAL("clicked()"), self.actionStart_Server.trigger)
        QtCore.QObject.connect(self.stopButton, QtCore.SIGNAL("clicked()"), self.actionStop_Serving.trigger)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "TFTP Server", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Server Directory:", None, QtGui.QApplication.UnicodeUTF8))
        self.selectFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Select the working directory.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.selectFolder.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFolder.setToolTip(QtGui.QApplication.translate("MainWindow", "<html><head/><body><p>Open a file browser at the current working folder.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.browseFolder.setText(QtGui.QApplication.translate("MainWindow", "Explore", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Network Address", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Port:", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.menuServer.setTitle(QtGui.QApplication.translate("MainWindow", "&Server", None, QtGui.QApplication.UnicodeUTF8))
        self.menuHelp.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStart_Server.setText(QtGui.QApplication.translate("MainWindow", "&Start Server", None, QtGui.QApplication.UnicodeUTF8))
        self.actionQuit.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAbout.setText(QtGui.QApplication.translate("MainWindow", "&About", None, QtGui.QApplication.UnicodeUTF8))
        self.actionStop_Serving.setText(QtGui.QApplication.translate("MainWindow", "Sto&p Serving", None, QtGui.QApplication.UnicodeUTF8))
        self.actionSettings.setText(QtGui.QApplication.translate("MainWindow", "S&ettings", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Working_Folder.setText(QtGui.QApplication.translate("MainWindow", "Open Working Folder", None, QtGui.QApplication.UnicodeUTF8))
        self.actionOpen_Working_Folder.setToolTip(QtGui.QApplication.translate("MainWindow", "Open working folder", None, QtGui.QApplication.UnicodeUTF8))

import TftpServer_rc
